# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies without running any scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the TypeScript code and ensure the entry point is executable
RUN npm run build

# Expose any relevant port if needed (MCP typically uses stdio, so may not be necessary)

# Set the default command to run the MCP server
CMD ["node", "build/index.js"]
