# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies (ignoring lifecycle scripts to speed up install if needed)
RUN npm install --ignore-scripts

# Copy source code and other necessary files
COPY . .

# Build the project
RUN npm run build

# Expose port if necessary (MCP typically uses stdio, so no port needed)

# Use an ENTRYPOINT that starts the server
ENTRYPOINT [ "node", "build/index.js" ]
